/**
 * Comprehensive catalog of Indian Cities, Union Territories, and Major Towns.
 * Covers Tier 1, Tier 2, and Tier 3 cities across all 28 States and 8 Union Territories.
 */
export const INDIAN_CITIES: string[] = [
  // Metro & Major Economic Hubs
  'Bengaluru',
  'Mumbai',
  'Delhi NCR',
  'New Delhi',
  'Hyderabad',
  'Chennai',
  'Kolkata',
  'Pune',
  'Ahmedabad',
  'Jaipur',
  'Surat',
  'Lucknow',
  'Kanpur',
  'Nagpur',
  'Indore',
  'Thane',
  'Bhopal',
  'Visakhapatnam',
  'Patna',
  'Vadodara',
  'Ghaziabad',
  'Ludhiana',
  'Agra',
  'Nashik',
  'Faridabad',
  'Meerut',
  'Rajkot',
  'Kalyan-Dombivli',
  'Vasai-Virar',
  'Varanasi',
  'Srinagar',
  'Aurangabad (Chhatrapati Sambhajinagar)',
  'Dhanbad',
  'Amritsar',
  'Navi Mumbai',
  'Prayagraj (Allahabad)',
  'Howrah',
  'Ranchi',
  'Gwalior',
  'Jabalpur',
  'Coimbatore',
  'Vijayawada',
  'Jodhpur',
  'Madurai',
  'Raipur',
  'Kota',
  'Guwahati',
  'Chandigarh',
  'Solapur',
  'Hubballi-Dharwad',
  'Bareilly',
  'Moradabad',
  'Mysuru (Mysore)',
  'Gurugram (Gurgaon)',
  'Noida',
  'Greater Noida',
  'Aligarh',
  'Jalandhar',
  'Tiruchirappalli (Trichy)',
  'Bhubaneswar',
  'Salem',
  'Warangal',
  'Mira-Bhayandar',
  'Thiruvananthapuram',
  'Bhiwandi',
  'Saharanpur',
  'Guntur',
  'Amravati',
  'Bikaner',
  'Nanded',
  'Kolhapur',
  'Ajmer',
  'Akola',
  'Gulbarga (Kalaburagi)',
  'Jamnagar',
  'Ujjain',
  'Loni',
  'Siliguri',
  'Jhansi',
  'Ulhasnagar',
  'Jammu',
  'Sangli-Miraj & Kupwad',
  'Mangaluru (Mangalore)',
  'Erode',
  'Belagavi (Belgaum)',
  'Ambattur',
  'Tirunelveli',
  'Malegaon',
  'Gaya',
  'Jalgaon',
  'Udaipur',
  'Maheshtala',
  'Davanagere',
  'Kozhikode (Calicut)',
  'Kurnool',
  'Rajpur Sonarpur',
  'Rajahmundry',
  'Bokaro Steel City',
  'South Dumdum',
  'Bellary (Ballari)',
  'Patiala',
  'Gopalpur',
  'Agartala',
  'Bhagalpur',
  'Muzaffarnagar',
  'Bhatpara',
  'Panihati',
  'Latur',
  'Dhule',
  'Rohtak',
  'Korba',
  'Bhilai',
  'Brahmapur',
  'Muzaffarpur',
  'Ahmednagar',
  'Mathura',
  'Kollam',
  'Avadi',
  'Kadapa',
  'Kamarhati',
  'Sambalpur',
  'Bilaspur',
  'Shahjahanpur',
  'Satara',
  'Bijapur (Vijayapura)',
  'Rampur',
  'Shivamogga (Shimoga)',
  'Chandrapur',
  'Junagadh',
  'Thrissur',
  'Alwar',
  'Bardhaman',
  'Kulti',
  'Kakinada',
  'Nizamabad',
  'Parbhani',
  'Tumakuru (Tumkur)',
  'Khammam',
  'Ozhukarai',
  'Bihar Sharif',
  'Panipat',
  'Darbhanga',
  'Bally',
  'Aizawl',
  'Dewas',
  'Ichalkaranji',
  'Karnal',
  'Bathinda',
  'Jalna',
  'Eluru',
  'Kirari Suleman Nagar',
  'Barasat',
  'Purnia',
  'Satna',
  'Mau',
  'Sonipat',
  'Farrukhabad',
  'Sagar',
  'Rourkela',
  'Durg',
  'Imphal',
  'Ratlam',
  'Hapur',
  'Arrah',
  'Karimnagar',
  'Anantapur',
  'Etawah',
  'Ambernath',
  'North Dumdum',
  'Bharatpur',
  'Begusarai',
  'New Delhi',
  'Gandhidham',
  'Baranagar',
  'Tiruvottiyur',
  'Puducherry (Pondicherry)',
  'Sikar',
  'Thoothukudi (Tuticorin)',
  'Rewa',
  'Mirzapur',
  'Raichur',
  'Pali',
  'Ramagundam',
  'Haridwar',
  'Vijayanagaram',
  'Katihar',
  'Nagarcoil',
  'Sri Ganganagar',
  'Karawal Nagar',
  'Mango',
  'Thanjavur',
  'Bulandshahr',
  'Uluberia',
  'Murwara (Katni)',
  'Sambhal',
  'Singrauli',
  'Nadiad',
  'Secunderabad',
  'Naihati',
  'Yamunanagar',
  'Bidhannagar',
  'Pallavaram',
  'Bidar',
  'Munger',
  'Panchkula',
  'Burhanpur',
  'Raurkela Industrial Township',
  'Kharagpur',
  'Dindigul',
  'Gandhinagar',
  'Hospet',
  'Nangloi Jat',
  'Malda',
  'Ongole',
  'Deoghar',
  'Chapra',
  'Haldia',
  'Khandwa',
  'Nandyal',
  'Chittoor',
  'Morena',
  'Amroha',
  'Anand',
  'Bhind',
  'Bhalswa Jahangir Pur',
  'Madhyamgram',
  'Bhiwani',
  'Navsari',
  'Bahraich',
  'Vellore',
  'Kochi (Cochin)',
  'Dehradun',
  'Shimla',
  'Shillong',
  'Gangtok',
  'Kohima',
  'Panaji',
  'Port Blair',
  'Diu',
  'Daman',
  'Silvassa',
  'Kavaratti',
  'Leh',
  'Kargil',
  'Rishikesh',
  'Mussoorie',
  'Manali',
  'Dharamshala',
  'Nainital',
  'Ooty',
  'Kodaikanal',
  'Munnar',
  'Alappuzha (Alleppey)',
  'Pondicherry',
  'Vapi',
  'Ankleshwar',
  'Bharuch',
  'Morbi',
  'Mehsana',
  'Surendranagar',
  'Porbandar',
  'Bhavnagar',
  'Haldwani',
  'Roorkee',
  'Rudrapur',
  'Kashipur',
  'Baddi',
  'Solan',
  'Mandi',
  'Palampur',
  'Kullu',
  'Pathankot',
  'Hoshiarpur',
  'Mohali',
  'Batala',
  'Abohar',
  'Moga',
  'Malerkotla',
  'Khanna',
  'Phagwara',
  'Muktsar',
  'Barnala',
  'Firozpur',
  'Kapurthala',
  'Ambala',
  'Hisar',
  'Karnal',
  'Sirsa',
  'Bahadurgarh',
  'Jind',
  'Thanesar',
  'Kaithal',
  'Rewari',
  'Palwal',
  'Jagadhri',
  'Hansi',
  'Narnaul',
  'Fatehabad',
  'Gohana',
  'Tohana',
  'Narwana',
  'Bhiwadi',
  'Beawar',
  'Hanumangarh',
  'Dholpur',
  'Sawai Madhopur',
  'Churu',
  'Barmer',
  'Makrana',
  'Nagaur',
  'Hindaun',
  'Kishangarh',
  'Sujangarh',
  'Jhunjhunu',
  'Chittorgarh',
  'Tonk',
  'Gangapur City',
  'Bhilwara',
  'Bundi',
  'Balotra',
  'Nimbahera',
  'Banswara',
  'Dungarpur',
  'Jalore',
  'Pratapgarh',
  'Jaisalmer',
];
